project:
  type: website
  output-dir: docs

book:
  title: "Using Digital Footprint Data to Measure and Monitor Human Mobility"
  author: "Prof. Francisco Rowe, Dr. Carmen Cabrera-Arnau, Dr. Miguel Gonzalez-Leonardo, Ruth Neville and Andrea Nasuto"
  date: "6/20/2023"
  chapters:
    - index.qmd
    - overview.qmd
    # - data-description.qmd
    # - exploring-temporal-data.qmd
    # - exploring-spatial-data.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme: journal
  pdf:
    documentclass: scrreprt

editor: visual

