project:
  type: book
  output-dir: docs

book:
  title: "Using Digital Footprint Data to Measure and Monitor Human Mobility"
  author: "Prof. Francisco Rowe, Dr. Carmen Cabrera-Arnau, Dr. Miguel Gonzalez-Leonardo, Ruth Neville and Andrea Nasuto"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - overview.qmd
    # - data-description.qmd
    # - temporal-trends.qmd
    # - spatial-patterns.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme: journal
  pdf:
    documentclass: scrreprt

editor: visual

