# Welcome {.unnumbered}

This website hosts the materials for the workshop *"Using Digital Footprint Data to Measure and Monitor Human Mobility"*. This training workshop was designed and is delivered by Prof. Francisco Rowe, Dr. Carmen Cabrera-Arnau, Dr. Miguel González-Leonardo, Ruth Neville and Andrea Nasuto.

The website is *free to use* and is licensed under the [Attribution-NonCommercial-NoDerivatives 4.0 International](https://creativecommons.org/licenses/by-nc-nd/4.0/). <!-- A compilation of this web course is hosted as a GitHub repository that you can access: -->

<!-- -   As a download of a `.zip` file that contains all the materials -->

<!-- -   As an html website -->

<!-- -   As a pdf document -->

<!-- -   As a GitHub repository -->

# Contact {.unnumbered}

> | Prof. Francisco Rowe, Professor in Population Data Science
> | f.rowe-gonzalez \[at\] liverpool.ac.uk
> | Department of Geography and Planning, University of Liverpool, Liverpool, UK

> | Dr Carmen Cabrera-Arnau, Lecturer in Geographic Data Science
> | c.cabrera-arnau \[at\] liverpool.ac.uk
> | Department of Geography and Planning, University of Liverpool, Liverpool, UK

> | Dr Miguel Gonzalez-Leonardo, Assistant Professor
> | miguel.gonzalez \[at\] colmex.mx
> | Center for Demographic, Urban and Environmental Studies, El Colegio de Mexico, Mexico City, Mexico

> | Ruth Neville, PhD candidate
> | ruth.neville \[at\] liverpool.ac.uk
> | Department of Geography and Planning, University of Liverpool, Liverpool, UK

> | Andrea Nasuto, PhD candidate
> | andrea.nasuto \[at\] liverpool.ac.uk
> | Department of Geography and Planning, University of Liverpool, Liverpool, UK
