project:
  type: book
  output-dir: docs

book:
  title: "Using Digital Footprint Data to Measure and Monitor Human Mobility"
  author: "Prof. Francisco Rowe, Dr. Carmen Cabrera-Arnau, Dr. Miguel Gonzalez-Leonardo, Ruth Neville and Andrea Nasuto"
  date: today
  chapters:
    - index.qmd
    - overview.qmd
    # - data-description.qmd
    # - temporal-trends.qmd
    - spatial-patterns.qmd
    # - references.qmd

  search: true
  site-url: https://fcorowe.github.io/dfd4mobility/
  repo-url: https://github.com/fcorowe/dfd4mobility

bibliography: references.bib

format:
  html:
    theme: journal
  pdf:
    documentclass: scrreprt

editor: visual

