# Overview {.unnumbered}

## Description

This workshop offers an introduction to the use of digital footprint data from Meta-Facebook to analyse internal population movements. We will cover how to use location data collected via digital technology to develop data products to analyse human mobility. We will also illustrate how these data can be used to create statistical indicators and geographic data visualisations to extract insightful information, monitor mobility trends and identify key areas of origin and destination. The workshop will use an applied, hands-on approach in R via computational notebooks.

## Structure

| Time        | Activity                                                    |
|----------------|--------------------------------------------------------|
| 9.00-9.30   | Registration and welcome coffee                             |
| 9.30-10.30  | Digital Footprint Data overview                             |
| 10.30-10.40 | Comfort break                                               |
| 10.40-11.40 | Meta-Facebook data introduction                             |
| 11.40-12.15 | Software installation and preparation for practical session |
| 12.15-13.15 | Lunch break                                                 |
| 13.15-14.30 | Exploring temporal patterns of human mobility               |
| 14.30-15.00 | Coffee break                                                |
| 15.00-16.30 | Exploring spatial patterns of human mobility                |
| 16.30-17.00 | Q&A                                                         |

## Before the workshop

::: callout-important
Please make sure you download and install the most recent version of R, RStudio and Quarto on the computer that you will be using during the workshop, and install the indicated R packages -- see detailed instructions below.
:::

::: callout-note
All three software packages are open and free to use.
:::

**R**

You can download R [here](https://cran.r-project.org/). Make sure you select the appropriate version for your Operating System: Windows, MacOS (Apple silicon M1/M2 or older intel Macs). For example, if you use a macOS laptop with an M1 processor, click on 'Download R for macOS' and then, click the link to download the installer file (.pkg extension for macOS) under the header 'For Apple silicon (M1/M2) Macs'. You can then open the installer and follow the instructions that you will be prompted with. For Windows users, click on '[install R for the first time](https://cran.r-project.org/bin/windows/base/)' and follow the prompts.

**RStudio**

You will also need to download RStudio Desktop (or simply RStudio), which is an integrated development environment to help you write code in R more easily. To download RStudio, follow this [link](https://posit.co/download/rstudio-desktop/) and scroll down to the section titled 'All Installers and Tarballs'. Download the appropriate installer file according to your Operating System. Then, open the installer and follow the installation instructions that you will be prompted with.

**Quarto**

Download Quarto from this [website](https://quarto.org/docs/get-started/). Quarto is a publishing system that will allow you to open and work on the computational notebooks for the workshop. On 'Step 1' on the website, download the version of Quarto that matches your Operating System. Open the installer file, run it and follow the prompts.

**R libraries**

Once you have installed R, you will need to install some R extensions, known as packages, that will be useful for the applications explored in this workshop. The packages you need to install are:

-   `tidyverse`
-   `ggthemes`
-   `patchwork`
-   `viridis`
-   `tmap`
-   `sf`
-   `sp`
-   `stringr`
-   `RColorBrewer`

To install the packages, open RStudio. On the console window (normally at the bottom left), write the following command: install.packages("name of package"). Make sure you replace "name of package" by the actual name of the package that you want to install e.g. install.packages("tidyverse"). Then, press enter and repeat this process until you have installed all the packages in the list.

::: callout-note
We might ask you to install more packages on the day that this workshop is taking place.
:::

## During the workshop

All the workshop material will be made available on this [website](https://fcorowe.github.io/dfd4mobility/) which is currently under construction. Further instructions on how to download the material will be given during the workshop.
